name: Scheduled Tests
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (For Appium)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Appium 1.x
        run: npm install -g appium@1.22.3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install EXACT dependencies
        run: |
          pip install Appium-Python-Client==1.3.0
          pip install selenium==3.141.0
          pip install urllib3==1.26.18
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Appium Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}  
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          script: |
            # 1. הפעלת שרת אפיום בדיוק על הפורט שלך
            appium --port 4724 &
            
            # המתנה קלה שהשרת יעלה
            sleep 10
            
            # 2. טריק ה-CI: החלפה זמנית של ה-UDID
            sed -i 's/RF8N63P9Z9R/emulator-5554/g' $(find . -name "conftest.py")
            
            # 3. התקנת האפליקציה על האמולטור הריק
            adb -s emulator-5554 install ApiDemos-debug.apk
            
            # 4. הרצת הטסטים יחד עם הגדרת נתיב הפרויקט באותה שורה!
            PYTHONPATH=$(pwd) xvfb-run pytest -s -v